import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import SocialAccounts from "../../components/SocialAccounts";
import AddNewSocialAccount from "../../components/AddNewSocialAccount";
import Verify from "../../components/Verify";
import PostDetails from "../../components/PostDetails";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { address, isConnected } = useAccount();

  const router = useRouter();
  const { hash } = router.query;
  
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <ConnectButton />
        <PostDetails postHash={hash as string} />
      </main>

      <footer>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your
        </a>
      </footer>
    </div>
  );
};

export default Home;
